/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-glass": "#131A22",
        surface: "#051424",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-lowest": "#010f1f",
        "on-primary-fixed-variant": "#005321",
        "border-subtle": "#1F2937",
        "surface-tint": "#4ae176",
        "on-surface": "#d4e4fa",
        "tertiary-fixed-dim": "#ffb95f",
        background: "#0B0F14",
        "on-secondary": "#002e6a",
        "primary-fixed-dim": "#4ae176",
        "inverse-primary": "#006e2f",
        "outline-variant": "#3d4a3d",
        "on-error": "#690005",
        "terminal-black": "#050B14",
        "on-primary": "#003915",
        "surface-container": "#122131",
        "error-container": "#93000a",
        "tertiary-container": "#ef9900",
        "inverse-surface": "#d4e4fa",
        "on-surface-variant": "#bccbb9",
        "on-tertiary-fixed": "#2a1700",
        "secondary-container": "#0566d9",
        "primary-fixed": "#6bff8f",
        "surface-container-high": "#1c2b3c",
        "on-tertiary-container": "#5c3800",
        "on-background": "#d4e4fa",
        "surface-dim": "#051424",
        outline: "#869585",
        "inverse-on-surface": "#233143",
        "on-secondary-container": "#e6ecff",
        secondary: "#adc6ff",
        "on-tertiary": "#472a00",
        "secondary-fixed-dim": "#adc6ff",
        "surface-bright": "#2c3a4c",
        "on-primary-fixed": "#002109",
        primary: "#4be277",
        "primary-container": "#22c55e",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#001a42",
        error: "#ffb4ab",
        "surface-container-highest": "#273647",
        "surface-variant": "#273647",
        tertiary: "#ffba61",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed": "#d8e2ff",
        "success-dim": "#4ae176",
        "surface-container-low": "#0d1c2d",
        "on-primary-container": "#004b1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "24px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        unit: "4px",
        "stack-sm": "8px",
        gutter: "24px",
        "stack-xl": "48px",
        "stack-xs": "4px",
        "container-max": "1440px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
